/**
 * Tailwind CSS Configuration
 * This file is auto-generated by design_system/integrate-config.ts
 * DO NOT EDIT MANUALLY - Changes will be overwritten
 * 
 * Last updated: 2026-02-12
 * 
 * Sources:
 * - design_system/generated-tailwind-config.json (Tailwind utilities from design tokens)
 * - tailwind.config.template (Base configuration)
 */

/** @type {import('tailwindcss').Config} */
export default {
	darkMode: ["class"],
	content: [
		"./index.html",
		"./src/**/*.{js,ts,jsx,tsx,html}"
	],
	theme: {
		extend: {
			fontFamily: {
				metawebpro: ['Metawebpro', 'system-ui', 'sans-serif'],
				'wwu-symbol': ['WWU Symbol', 'system-ui', 'sans-serif'],
				primary: ['Meta', 'system-ui', 'sans-serif']
			},
			colors: {
				blue: {
					'100': 'hsl(var(--blue-100))',
					'200': 'hsl(var(--blue-200))',
					'300': 'hsl(var(--blue-300))',
					'400': 'hsl(var(--blue-400))',
					'500': 'hsl(var(--blue-500))',
					'600': 'hsl(var(--blue-600))',
					'700': 'hsl(var(--blue-700))',
					'800': 'hsl(var(--blue-800))',
					'900': 'hsl(var(--blue-900))',
					'950': 'hsl(var(--blue-950))',
					'050': 'hsl(var(--blue-050))'
				},
				white: 'hsl(var(--white))',
				rose: {
					'100': 'hsl(var(--rose-100))',
					'200': 'hsl(var(--rose-200))',
					'300': 'hsl(var(--rose-300))',
					'400': 'hsl(var(--rose-400))',
					'500': 'hsl(var(--rose-500))',
					'600': 'hsl(var(--rose-600))',
					'700': 'hsl(var(--rose-700))',
					'800': 'hsl(var(--rose-800))',
					'900': 'hsl(var(--rose-900))',
					'950': 'hsl(var(--rose-950))',
					'050': 'hsl(var(--rose-050))'
				},
				violet: {
					'100': 'hsl(var(--violet-100))',
					'200': 'hsl(var(--violet-200))',
					'300': 'hsl(var(--violet-300))',
					'400': 'hsl(var(--violet-400))',
					'500': 'hsl(var(--violet-500))',
					'600': 'hsl(var(--violet-600))',
					'700': 'hsl(var(--violet-700))',
					'800': 'hsl(var(--violet-800))',
					'900': 'hsl(var(--violet-900))',
					'950': 'hsl(var(--violet-950))',
					'050': 'hsl(var(--violet-050))'
				},
				fdm: {
					blue: {
						'100': 'hsl(var(--fdm-blue-100))',
						'200': 'hsl(var(--fdm-blue-200))',
						'300': 'hsl(var(--fdm-blue-300))',
						'400': 'hsl(var(--fdm-blue-400))',
						'500': 'hsl(var(--fdm-blue-500))',
						'600': 'hsl(var(--fdm-blue-600))',
						'700': 'hsl(var(--fdm-blue-700))',
						'800': 'hsl(var(--fdm-blue-800))',
						'900': 'hsl(var(--fdm-blue-900))',
						'950': 'hsl(var(--fdm-blue-950))',
						'050': 'hsl(var(--fdm-blue-050))'
					}
				},
				yellow: {
					'100': 'hsl(var(--yellow-100))',
					'200': 'hsl(var(--yellow-200))',
					'300': 'hsl(var(--yellow-300))',
					'400': 'hsl(var(--yellow-400))',
					'500': 'hsl(var(--yellow-500))',
					'600': 'hsl(var(--yellow-600))',
					'700': 'hsl(var(--yellow-700))',
					'800': 'hsl(var(--yellow-800))',
					'900': 'hsl(var(--yellow-900))',
					'950': 'hsl(var(--yellow-950))',
					'050': 'hsl(var(--yellow-050))'
				},
				ulb: {
					grey: {
						'100': 'hsl(var(--ulb-grey-100))',
						'200': 'hsl(var(--ulb-grey-200))',
						'300': 'hsl(var(--ulb-grey-300))',
						'400': 'hsl(var(--ulb-grey-400))',
						'500': 'hsl(var(--ulb-grey-500))',
						'600': 'hsl(var(--ulb-grey-600))',
						'700': 'hsl(var(--ulb-grey-700))',
						'800': 'hsl(var(--ulb-grey-800))',
						'900': 'hsl(var(--ulb-grey-900))',
						'950': 'hsl(var(--ulb-grey-950))',
						'050': 'hsl(var(--ulb-grey-050))'
					},
					red: {
						'100': 'hsl(var(--ulb-red-100))',
						'200': 'hsl(var(--ulb-red-200))',
						'300': 'hsl(var(--ulb-red-300))',
						'400': 'hsl(var(--ulb-red-400))',
						'500': 'hsl(var(--ulb-red-500))',
						'600': 'hsl(var(--ulb-red-600))',
						'700': 'hsl(var(--ulb-red-700))',
						'800': 'hsl(var(--ulb-red-800))',
						'900': 'hsl(var(--ulb-red-900))',
						'950': 'hsl(var(--ulb-red-950))',
						'050': 'hsl(var(--ulb-red-050))'
					}
				},
				scdh: {
					blue: {
						'100': 'hsl(var(--scdh-blue-100))',
						'200': 'hsl(var(--scdh-blue-200))',
						'300': 'hsl(var(--scdh-blue-300))',
						'400': 'hsl(var(--scdh-blue-400))',
						'500': 'hsl(var(--scdh-blue-500))',
						'600': 'hsl(var(--scdh-blue-600))',
						'700': 'hsl(var(--scdh-blue-700))',
						'800': 'hsl(var(--scdh-blue-800))',
						'900': 'hsl(var(--scdh-blue-900))',
						'950': 'hsl(var(--scdh-blue-950))',
						'050': 'hsl(var(--scdh-blue-050))'
					}
				},
				pink: {
					'100': 'hsl(var(--pink-100))',
					'200': 'hsl(var(--pink-200))',
					'300': 'hsl(var(--pink-300))',
					'400': 'hsl(var(--pink-400))',
					'500': 'hsl(var(--pink-500))',
					'600': 'hsl(var(--pink-600))',
					'700': 'hsl(var(--pink-700))',
					'800': 'hsl(var(--pink-800))',
					'900': 'hsl(var(--pink-900))',
					'950': 'hsl(var(--pink-950))',
					'050': 'hsl(var(--pink-050))'
				},
				green: {
					'100': 'hsl(var(--green-100))',
					'200': 'hsl(var(--green-200))',
					'300': 'hsl(var(--green-300))',
					'400': 'hsl(var(--green-400))',
					'500': 'hsl(var(--green-500))',
					'600': 'hsl(var(--green-600))',
					'700': 'hsl(var(--green-700))',
					'800': 'hsl(var(--green-800))',
					'900': 'hsl(var(--green-900))',
					'950': 'hsl(var(--green-950))',
					'050': 'hsl(var(--green-050))'
				},
				red: {
					'100': 'hsl(var(--red-100))',
					'200': 'hsl(var(--red-200))',
					'300': 'hsl(var(--red-300))',
					'400': 'hsl(var(--red-400))',
					'500': 'hsl(var(--red-500))',
					'600': 'hsl(var(--red-600))',
					'700': 'hsl(var(--red-700))',
					'800': 'hsl(var(--red-800))',
					'900': 'hsl(var(--red-900))',
					'950': 'hsl(var(--red-950))',
					'050': 'hsl(var(--red-050))'
				},
				tan: {
					'100': 'hsl(var(--tan-100))',
					'200': 'hsl(var(--tan-200))',
					'300': 'hsl(var(--tan-300))',
					'400': 'hsl(var(--tan-400))',
					'500': 'hsl(var(--tan-500))',
					'600': 'hsl(var(--tan-600))',
					'700': 'hsl(var(--tan-700))',
					'800': 'hsl(var(--tan-800))',
					'900': 'hsl(var(--tan-900))',
					'950': 'hsl(var(--tan-950))',
					'050': 'hsl(var(--tan-050))'
				},
				black: 'hsl(var(--black))'
			},
			spacing: {
				'100': 'var(--space-linear-100)',
				'125': 'var(--space-linear-125)',
				'150': 'var(--space-linear-150)',
				'200': 'var(--space-linear-200)',
				'300': 'var(--space-linear-300)',
				'400': 'var(--space-linear-400)',
				'500': 'var(--space-linear-500)',
				'550': 'var(--space-linear-550)',
				'600': 'var(--space-linear-600)',
				'700': 'var(--space-linear-700)',
				'750': 'var(--space-linear-750)',
				'800': 'var(--space-linear-800)',
				'900': 'var(--space-linear-900)',
				'050': 'var(--space-linear-050)',
				'075': 'var(--space-linear-075)',
				'025': 'var(--space-linear-025)'
			},
			borderRadius: {
				none: 'var(--radius-none)',
				xs: 'var(--radius-xs)',
				md: 'var(--radius-md)',
				'3xl': 'var(--radius-3xl)',
				'4xl': 'var(--radius-4xl)',
				'2xl': 'var(--radius-2xl)',
				lg: 'var(--radius-lg)',
				full: 'var(--radius-full)',
				xl: 'var(--radius-xl)',
				sm: 'var(--radius-sm)'
			},
			fontSize: {
				sm: [
					'var(--font-size-sm)',
					{
						lineHeight: '1.5'
					}
				],
				md: [
					'var(--font-size-md)',
					{
						lineHeight: '1.5'
					}
				],
				lg: [
					'var(--font-size-lg)',
					{
						lineHeight: '1.5'
					}
				],
				xl: [
					'var(--font-size-xl)',
					{
						lineHeight: '1.5'
					}
				],
				'2xl': [
					'var(--font-size-2xl)',
					{
						lineHeight: '1.5'
					}
				],
				'3xl': [
					'var(--font-size-3xl)',
					{
						lineHeight: '1.5'
					}
				]
			}
		}
	},
	plugins: [require("tailwindcss-animate")],
}
